jwt:
  secret: abcdefghabcdefghabcdefghabcdefghabcdefghabcdefefeq

spring:
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: ${SERVER_PORT}