jwt:
  key: ${PRIVATE_KEY}
reservation:
  url: ${RESERVATION_URL}
  port: ${RESERVATION_PORT}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
server:
  port: ${SERVER_PORT}