#jwt:
#  key: "./private-key.pem"
reservation:
  url: ${RESERVATION_URL}
  port: ${RESERVATION_PORT}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT}